### ISSUE TITLE
SSR - Use Only component cause generation different HTML on server and client

### ISSUE THREAD

**Issue by lokhmakov** [kettanaito/atomic-layout#117]
## What:

When using a component Only server HTML may differ from generated on client with warning: 

```
Warning: Expected server HTML to contain a matching <div> in <div>.
```

## Environment:

- node vesrion: `10.15.0`
- npm version: `6.4.1`
- atomic-layout version: `0.6.2`

## Steps to reproduce:

Create component on server with such composition:

```
      <Composition
        template={templateMobile}
        templateMd={templateTablet}
        templateLg={templateMobile}
        templateColsMdOnly='minmax(100px, 1fr) 1fr'
        padding={15}
        gutter={15}
        gutterLg={25}
      >
        {({ Thumbnail, Heading, Actions }) => (
          <>
            <Thumbnail>
              Thumbnail
            </Thumbnail>
            <Heading>
              Heading
            </Heading>
            <Actions>
              <Only from='md' marginRight={10}>
                Button
              </Only>
              Actions
            </Actions>
          </>
        )}
      </Composition>
```

**Comment by redraushan** [comment]
Hi @lokhmakov,

1. Could you please test if the same warning is appearing in case of not using `atomic-layout`? 
2. Test if same warning is appearing in prod mode as well?

I believe the issue is not directly related with `atomic-layout` but the way SSR has been implemented in the base application. 

It is most likely because of the reason that server doesn't render anything during the `dev` phase. We shouldn’t call hydrate when we are in  `dev` mode and only call `hydrate` during `prod`.

Similar issue has been observed by others in their SSR apps, please refer the following issue:
https://github.com/nozzle/react-static/issues/144

Hi @kettanaito  what do you think?

Thanks

**Comment by lokhmakov** [comment]
@redraushan If remove Only component HTML generated by NextJS the same as generated by react after delivery in browser.

I will (2) test it a little later.

**Comment by lokhmakov** [comment]
In production the same, but without warning because disabled in react in production mode.

**Comment by bitttttten** [comment]
What does your render method on the client look like?

It should look *something* like

```js
import { hydrate, render } from 'react-dom'

const method = typeof window === "undefined" ? render : hydrate

method(
  <App />,
  document.getElementById('root')
)
```

**Comment by lokhmakov** [comment]
@bitttttten We use NextJS default without any customization.

**Comment by lokhmakov** [comment]
Where is for initial render on client is used hydrate.

https://github.com/zeit/next.js/blob/75476a91362d6dc4e9fe7bda103adeab1e81f2d8/client/index.js#L201

**Comment by kettanaito** [comment]
I think the issue of mismatched nodes happens due to `Only` component's default behavior (which in this case is the server behavior as well). It's not a problem with the project/SSR setup.

Imagine you are rendering:

```jsx
<Only from="md">...</Only>
```

While on runtime it's easy to determine the viewport, a server must assume it to provide conditional rendering of the components tree. There is no way to know if a "md" breakpoint satisfies the current viewport, because there is no viewport on the server. This is not an issue per say, but a specificity of server-side rendering. I should look how other solutions tackle this problem.

I know that `react-responsive` lets *you* [assume the default viewport](https://github.com/contra/react-responsive#server-rendering) via props on server-side. However, I don't think this would solve the issue, since the assumed breakpoint is not guaranteed to be the end client-side breakpoint, difference in which produces nodes mismatch.

Unfortunately, I don't operate with the knowledge on how to solve it for your case, @lokhmakov. This is a conceptual question, and I'm open to any suggestion. This is most likely going to be the library's API in the future.

**Comment by bitttttten** [comment]
One way to solve it is to always let Only render it's children, and hide it through CSS. Then hydration will not be a problem.

**Comment by kettanaito** [comment]
@bitttttten, that would, however, mean shipping unused HTML. I don't think this is a good idea, since React has a benefit of true conditional rendering, preserving bandwidth and performance. Moreover, I would say it's quite practical to conditionally render "smart" components, that operate with data upon mounting. Rendering them always to cover one warning, and raising a few others isn't going to work.

**Comment by bitttttten** [comment]
Fair points, so it looks like there are pros and cons 😅 

I guess @lokhmakov will have to rethink the way he is using `Only` or live with the hydration warnings (which may or may not lead to issues).

**Comment by kettanaito** [comment]
The biggest effect of the failed hydration is that React would need to throw away the server-side rendered chunk of the components tree and render the latest (client-side) part anew. When rendering deep node trees conditionally this may results into performance issues.

However, I think if we disable all conditional areas on the server-side (by making them `matches: false` by default), this would mean server hasn't spent any extra resources to render those areas, even if deeply branched. Then client hydration would fail, but there won't be a significant performance loss. 

Regardless, conditional rendering and hydration is quite a bigger topic, and I've tried to get some insights about this on Twitter, but haven't received any replies yet. This doesn't concern Atomic layout alone, in general: "_How would you hydrate a portion of a tree that is rendered depending on a breakpoint?_"

**Comment by lokhmakov** [comment]
> I think if we disable all conditional areas on the server-side.

@kettanaito Yep, with maybe one more recommendation from Dan is additional render on client through change state / props. https://github.com/facebook/react/issues/10591#issuecomment-334429627

**Comment by kettanaito** [comment]
Thanks, @lokhmakov. I will try to utilize that pattern, but I'm afraid conditional rendering on cDM implies "jumping" behavior in the UI.

The upcoming changes will behave as I described, by ignoring conditional areas on server-side:

https://github.com/kettanaito/atomic-layout/blob/c05faec7d115e7085e9886a3c61a632db87be9e7/src/components/MediaQuery.tsx#L33-L42

I've finished with the manual testing, and will switch to testing with SSR.

**Comment by kettanaito** [comment]
After performing testing with SSR I can conclude that mismatch error on hydration is still there.

Here are a few possible solutions for the library to handle this:

1. Evaluate conditional client-side rendering on `componentDidMount`.
**Pros:** No nodes mismatch, both server and client will render *nothing*, until component is mounted client-side.
**Cons:** This would result into jumps on UI once component is mounted. However, when nothing is rendered on a server, and instantly rendered on a client—that's a jump as well.

2. Set `suppressHydrationWarning={true}` prop on `Only` component, preventing mismatch errors stating that they are expected.
**Pros:** Eliminates the warning. Since it's one level deep, should not interfere with other hydration warnings down the children tree (if even possible).
**Cons:** Is not meant to be used widely.

**Comment by lokhmakov** [comment]
> Evaluate conditional client-side rendering on componentDidMount

I think such solution may badly affect SEO.

> Set suppressHydrationWarning={true}

I choose this one! )

**Comment by kettanaito** [comment]
@lokhmakov, why do you think SEO would suffer with the first option? I believe the only way SEO could suffer is when the HTML consumed by it doesn't contain a certain content. However, with both of those options it will not contain conditionally rendered content.

I've discovered an interesting behavior with conditional rendering. Imagine this:

```jsx
<Only from="md">Foo</Only>
<Box padding={10}>Bar</Box>
```

The server-side HTML returns only `Box`, and when the client-side tries to hydrate the entire tree it *attaches Box props to the `Only` component*, making it inherit styles and properties that don't belong to it. I believe this is a strong argument to go with the conditional client-side rendering through `componentDidMount`.

I've tried the latter, and it works without an issues. No warnings, and no weird nodes behavior. I think we will stick to it until a better solution is present.

**Comment by bitttttten** [comment]
What's the use case where you are rendering critical information conditonally? I am trying to understand it since, apart from the increasing the volume of data and negatively affecting the initial payload, it will solve all the issues listed.

For the record, I have never had to conditionally render large trees. I am thinking more of a header with text links, and for example, on mobile and tablet there are icons also rendered under the text. In my view, I am be okay with sacraficing sending down icons in the HTML to desktop users who never see the icons so that there are no hydration issues, or jumpy UI on mobile. Also take into consideration that the icons would still be sent to the desktop view as part of the Javascript in the bundle. So the only added bandwidth is in rendering the svg html.

Once again, just looking to understand the use cases here so I can try and offer better advice :)

I can agree that React does conditional rendering very well so it's a big shame to loose the performance benefit here.. that's a tough one to let go in some situations.

**Comment by kettanaito** [comment]
@bitttttten Why not let the end developer decide the behavior they want using the library's API?

I mean, your use case is valid, just as mine. So, maybe the library should allow to specify which behavior the developer wants. Something like:

```jsx
<Only visuallyHidden from="md">Still rendered, just hidden</Only>
```

This would make the `Only` component smarter, but allow all use cases towards conditional rendering. `visuallyHidden` can also be recommended for SSR to avoid nodes mismatch.

**Comment by bitttttten** [comment]
That works for me 😃 

And it also removes the depency of the client side loading problem out of atomic-layout.

I think you could even make your own hook and use that for client side rendering instead:

```js
function useIsClientOnly() {
	const [isClientOnly,set] = useState(false)

	useEffect(() => {
		set(true)
	}, [])

	return isClientOnly
}

function App() {
	const isClientOnly = useIsClientOnly()

	return (
		<>
			{..}
			{isClientOnly && <Something />
			{..}
		</>
	)
}
```

Maybe you could go from here @lokhmakov ?

**Comment by kettanaito** [comment]
I've moved the `visible` modifier suggestion to a separate ticket (#134), since it increases the complexity of the current solution.

As of now, I am going to go with the suggestion solution from React time, which means that responsive component will never render on server, and won't initially render on client. Client-side will evaluate the associated media query upon mount, and resolve the next render state only then. This will result into delay in render, but until a more suitable solution is found I would stick with this for the sake of keeping SSR working.

**Comment by lokhmakov** [comment]
@bitttttten Yep, for client dependent code like `pixi.js` or `atomic-layout/Only` we using dynamic import and all works fine, like:

```
import loadable from '@loadable/component'

const SectionTools = loadable(() =>
  import(`box/2d-editor/editor/web/section/SectionTools`),
)
```

**Comment by kettanaito** [comment]
According to our discussion I have set the default value for conditional rendering to be `false`. This means the conditional content will not be rendered on a server-side, and will not be rendered initially on the client-side as well (to retain proper nodes hydration). After `Only` component mounting it will re-match the current media query, and re-render the conditional content in case a match occurs.

Published under https://github.com/kettanaito/atomic-layout/releases/tag/0.7.1.
