### ISSUE TITLE
Rename gutter prop to match css API

### ISSUE THREAD

**Issue by pkrawc** [kettanaito/atomic-layout#188]
Why change the name of something already being learned by so many as part of the official css spec. `gutter` makes less sense than `gap` anyway.

**Comment by kettanaito** [comment]
Hi, @pkrawc. Thanks for raising this concern.

Compliance with CSS spec is one of the top priorities, that's why we've introduced `gap` (and its derived properties) as prop alias:

https://github.com/kettanaito/atomic-layout/blob/e0811483ccd7981a0b43d5d8af6cdc152ff4292e/src/const/propAliases.ts#L68-L79

You can use `gap`, `gapRow` and `gapCol` instead of respective `gutter` props. The values they accept are the same. `gutter` prop is still around and will be deprecated in the next releases. It seems that the README should be updated to use `gap` instead.

**Comment by kettanaito** [comment]
README updated in fe32235.
