### ISSUE TITLE
'Only' doesn't work

### ISSUE THREAD

**Issue by dandelionadia** [kettanaito/atomic-layout#195]
## What:
I want to have menu on big screen and burger on mobile. But burger exist for all screens.
![Screenshot (439)](https://user-images.githubusercontent.com/33199975/60799072-b9610e00-a172-11e9-94bf-7043851a909c.png)
![Screenshot (440)](https://user-images.githubusercontent.com/33199975/60799073-b9610e00-a172-11e9-8a44-4fd8133fdbd4.png)
![Screenshot (441)](https://user-images.githubusercontent.com/33199975/60799074-b9610e00-a172-11e9-9ff7-0351ba81471c.png)

**Comment by kettanaito** [comment]
Hello, @dandelionadia. Thanks for reporting this issue.

That's really unexpected, I would need to look into this issue.

**Comment by kettanaito** [comment]
Providing technical insights about the issue.

The issue originated in the `Only` component. Upon further discovery, it was evident that only the `to` prop is affected. This prop uses `closeBreakpoint` that performed the following transformations of the given breakpoint properties:

https://github.com/kettanaito/atomic-layout/blob/876765f2657a01c9b1bedf3bdc9c6ed5d41545a1/src/utils/breakpoints/closeBreakpoint/closeBreakpoint.ts#L32-L34

Whenever given an explicit string like `"576px"`, it would parse it to float (`576`), subtract 1 and return as-is, remaining a number. When a custom measurement unit is used that number is later suffixed with the unit, becoming `575 + "rem" = "575rem"`, which is not the expected behavior.

To solve this I'm adding a parsing of a breakpoint property into raw numeric value and unit, so it's possible to join them after `closeBreakpoint` is finished, preserving original measurement unit.

**Comment by kettanaito** [comment]
The issue is fixed in the version `0.9.1`. Thank you once more for reporting!

**Comment by dandelionadia** [comment]
Before component was everywhere and now it is not defined.

**Comment by dandelionadia** [comment]
No. it's okay now. 
I am sorry :)
