### ISSUE TITLE
ESM: "__PROD__" is not defined (non-existing area rendering)

### ISSUE THREAD

**Issue by dandelionadia** [kettanaito/atomic-layout#199]
## What:
error when rendering
```
ReferenceError: __PROD__ is not defined
get
C:/Users/nadia/Documents/projects/village-nature/node_modules/atomic-layout/esm/index.js:875
  872 | } // @ts-ignore-line
  873 | 
  874 | 
> 875 | if (!__PROD__) {
      | ^  876 |   console.warn('Prevented render of the area "%s", which is not found in the template definition. Please render one of the existing areas ("%s"), or modify the template to include "%s".', areaName, areas
  877 |   /* Filter out "." placeholder from the list of areas */
  878 |   .filter(singleAreaName => /\w+/.test(singleAreaName))
```

## Why:
when I forgot  to add {} in  {( Title, Image, Foo ) => ()} I have got error
```jsx
const About = () => (
    <Composition
        areas={areasMobile}
        areasMd={areasTablet}
        padding={2}
    >
        {( Title, Image, Foo ) => (
            <>
                <GlobalStyle bgColor="#FFFFFF" />
                <Title>About</Title>
                <Image>
                    <img src="https://cdn.dribbble.com/users/1355613/screenshots/6141198/fishing.jpg" alt="img" />
                </Image>
                <Foo>foo</Foo>
            </>
        )}
    </Composition>
)
```

**Comment by kettanaito** [comment]
Thank you, @dandelionadia. 

That looks like an issue with the `__PROD__` environmental flag. Perhaps it's not evaluated during the bundling and injected as-is, instead of its value.

This issue is reproducible when using the "weak" areas feature: rendering an area that is not defined in the areas template:

```jsx
<Composition areas="foo">
  {({ Bar }) => (
    <>
      <Bar />
    </>
  )}
</Composition> 
```

Proxying the areas Object gives a friendly warning when rendering undefined areas (in case it's unintentional). A part of the code that produces the warning relies on the `__PROD__` variable to determine whether this warning must be logged (no warnings in production).

https://github.com/kettanaito/atomic-layout/blob/5ab14be2cc4f615ed404fb836e5b46aaab86495a/src/utils/templates/generateComponents/generateComponents.tsx#L96-L101

I would need to set up an integration scenario to catch this error and fix it by properly configuring Rollup build.

**Comment by kettanaito** [comment]
Starting from `0.9.2` all module definitions of the library replace the environmental flags so they are not present in the end bundle. Please update and see if your issue is gone. Thanks.
