### ISSUE TITLE
contribution to atomic-layout docs

### ISSUE THREAD

**Issue by ruhaise** [kettanaito/atomic-layout#273]
## What:
How to contribute to atomic-layout docs as a contributor?  I couldn't find any documentation to do so

## Why:
I think it's necessary to add this for contributors too, so it's easy to share ideas and make the docs up-to-date more efficiently. perhaps it's a good idea to add the docs repo to the mono repo structure too since its tightly connected to the project, I'm not sure about this,

**Comment by kettanaito** [comment]
Thank for raising this. This is a valid concern and it will be addressed in #237. Please see that issue for more detailed reason of why contributing to docs is currently hard (if not impossible).

I'm closing this because there are no guidelines to write as the contribution process is not clear yet.
