### ISSUE TITLE
Error when running the Getting Started example

### ISSUE THREAD

**Issue by Hermanya** [kettanaito/atomic-layout#46]
## What
1. `Syntax Error: Unexpected character '​' (7:0)`
2. Layout is not defined
2. Element type is invalid: expected a string

## Why
1. Invisible characters in the docs example code
2. Layout -> Composition
3. React.Fragment -> Array of children (gatsby gave me react 16.3.2)

## Environment
* node vesrion: `8.9.4`
* npm version: `6.1.0`
* atomic-layout version: `0.3.4`
* mac: `10.13.5`
* react: `16.3.2`

## Steps to reproduce
1. I used gatsby for boilerplate
2. Copy code snippet from get started page in the docs
3. Mock card components
4. See errors

## Expected behavior
See the card example

I also tried https://styled-css-grid.js.org/ I like their api better (the cell approach), but it does not seem to support break points. 
Other than that your project looks great! 👍 Good step at making css grid more developer friendly.

**Comment by kettanaito** [comment]
Hi, @Hermanya. Thanks for the feedback.

Indeed, the example in the documentation uses an obsolete API. My apologies on that, the library is still in the early development, so there may be misleading parts in the docs.

I will edit the docs right now so that all code snippets include the API of the current released version.

**Comment by kettanaito** [comment]
Please see the [Getting started](https://redd.gitbook.io/atomic-layout/general/getting-started) page now.

Note that we have adopted the `Composition` component since it reflects the domain and purpose of the component better:

```jsx
import { Composition } from 'atomic-layout'
```

**However**, we still expose a `Layout` namespace, which is a global object used for providing library configurations:

```jsx
import Layout from 'atomic-layout'

Layout.configure({ ... })
```

See more on the [`Layout`](https://redd.gitbook.io/atomic-layout/api/layout) in the docs.

---

Thanks once more for notifying about that!
