### ISSUE TITLE
Cleanly handle components not included in grid templates

### ISSUE THREAD

**Issue by garth** [kettanaito/atomic-layout#78]
## What

Gracefully handle components that are not included in the current grid template(s)

## Why

For example, when using atomic-layout as a top level routing component, not all components will be included in the template, which means that each has to be checked to see if it's defined before it can be used.

```jsx
<Composition template={router.gridTemplate || `notFound`}>
{({ Page1, Page2, NotFound }) => (
  <>
    {Page1 && (
      <Page1>
        <Page1Component />
      </Page1>
    )}
    {Page2 && (
      <Page2>
        <Page2Component />
      </Page2>
    )}
    {NotFound && (
      <NotFound>
        <NotFoundComponent />
      </NotFound>
    )}
  </>
)}
</Composition>
```

## How

This could more cleanly be describe with a hash of components (indexed by template area)

```tsx
<Composition template={router.gridTemplate || `notFound`} components={{
  'page1': Page1Component,
  'page2': Page2Component,
  'notFound': NotFoundComponent,
}} />
```

or by using a more generic Area wrapper

```tsx
<Composition template={router.gridTemplate || `notFound`}>
  <Area name='page1'>
    <Page1Component />
  </Area>
  <Area name='page2'>
    <Page2Component />
   </Area>
  <Area name='notFound'>
    <NotFoundComponent />
  </Area>
</Composition>
```

**Comment by garth** [comment]
Since my example above is very basic (only two pages and no real grid usage), the benefits might not be evident, but here's a more "real world" setup, together with my current workaround:

```jsx
const components = {
  Header,
  Footer,
  Sidebar,
  Faq,
  Tabs,
  {...etc},
  NotFound
}

<Composition template={router.gridTemplate || `header
notFound
footer`}>
  {areas => (
    <>
      {Object.keys(components)
        .filter(name => areas[name])
        .map(name => ({ name, Area: areas[name], Component: components[name] }))
        .map(({ name, Area, Component }) => (
          <Area key={name}>
            <Component />
          </Area>
        ))}
    </>
  )}
</Composition>
```

**Comment by kettanaito** [comment]
Hello, @garth. Thank you for the detailed proposal!

I was thinking for a while how to properly handle the attempts to render area components that are not present in any of template definitions. The problem is that there is no way to know which keys have been referenced from the exposed are components Object, to validate the referenced areas. I would like to explicitly avoid the usage of Proxy due to its browser support.

Your `<Area/>` example looks interesting. I need to weight out what changes it would bring to the current architecture. Having a delegated point of render would allow to do:

1. Check `Area.props.name` is included in the unique list of area names.
2. Explicitly render `null` and give a developer-friendly warning that the referenced area is not specified in the template definitions.

What I don't like is that it would introduce an extra layer of API (the necessity to use "Area" component), as opposed to simply calling children of a Composition as a function.

Do you have some ideas how to validate areas references otherwise?

**Comment by garth** [comment]
I would suggest that using `<Area name='areaName' />` is more idiomatic React than using a function. Having read through the internals it's clear how the function params are created, but from outside it's not so easy to understand how it works.

Also, in most cases I would expect that there would already be a component with the same name, so you are more likely to have naming collisions. For example if I want to render `<Header/>` in my grid in the area called `header`, I now have two components called header, so I'll have to rename one of them. Using `<Area .../>` or similar would fix this.

One related issue that I don't have a good solution for is how to handle when no components/areas are rendered. Maybe some kind of default to fall back to would be useful?

I'm not sure I understand you last question?

**Comment by kettanaito** [comment]
One thing against `<Area/>` would be that it negates the automatic association between a component and the respective grid area. What I mean is that if you render a `<Header/>` component, you can safely assume that it's already associated with the grid area "header". There won't be such assumption when using a generic `<Area/>`.

Naming collisions is a good call, I'm thinking on how to avoid those. The next release is going to introduce a polymorphic components support (from styled-components), so it's possible to use:

```js
<Header as="header"/>
```

I would also assume it should be possible to supply a custom component as the value of that prop.

**Comment by garth** [comment]
This is my latest iteration to make it as simple as possible (also made a simple hook to get the responsive size):
```jsx
import { Grid, layout } from 'react-grid-area'
import useResponive from '../hooks/useResponive'

const page = {
  sm: layout`
    "${Header}" auto
    "${Home}"   1fr
    "${Footer}" auto`,
  md: layout`
    "${Header} ${Header}" auto
    "${Menu}   ${Home}"   1fr
    "${Footer} ${Footer}" auto / auto 1fr`,
 lg: layout`
    "${Header} ${Header}" auto
    "${Menu}   ${Home}"   1fr
    "${Footer} ${Footer}" auto / auto 1fr`
}

export const App = () => (
  const size = useResponive({ sm: 480, md: 1280 }, 'lg')
  return <Grid layout={page[size]} />
)
```
As you can see the grid and responsive implementations are completely independent and the code behind is very minimal.

With this setup, `<Area />` becomes redundant since we just render the components defined in each layout and add a css area name which is extracted as the component name by the layout template string.

And since any pre-processing is done, one time, by they layout template string outside the render, the render is very fast.

**Comment by kettanaito** [comment]
After testing the current implementation on Internet Explorer 11, I can confirm that quite a vital part of CSS Grid spec is not supported. Therefore, I've decided to ditch the support of IE entirely, and get benefit from using Proxy:

* Introduce proxying of areas Object, which will allow to warn developers on attempts to render undefined grid areas, and also prevent React rendering exception as well.
* Support dynamic templates, mainly due to the previous point.

I'm working on this change for some time now, and I think it will be available in the next minor version.
